#include <iostream.h>
#include <stdio.h>
#include <conio.h>
main(){
	char nama[10],input;
   int absen;
cout<<"input nama anda	:";gets(nama);
cout<<"input absen anda :";cin>>absen;
endl;
cout<<"======================"<<endl;
cout<<"       biodata       "<<endl;
cout<<"====================="<<endl;
cout<<"nama anda   :"<<nama<<endl;
cout<<"absen anda  :"<<absen<<endl;
cout<<"====================="<<endl;
getch();
}


